"""Generate the four-page public Forge website from canonical product metadata."""
from __future__ import annotations
import argparse, hashlib, html, json, shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; SITE=ROOT/'docs-site'; PRODUCT=json.loads((ROOT/'FORGE-PRODUCT.json').read_text()); WEB=PRODUCT['website']; VERSION=PRODUCT['version']; BASE=WEB['base_url'].rstrip('/')
def esc(v): return html.escape(str(v),quote=True)
def prefix(depth): return '../'*depth
def canonical(path): path=path.strip('/'); return f"{BASE}/{path+'/' if path else ''}"
def logo(p=''): return f'<span class="brand-mark" aria-hidden="true"><img src="{p}assets/forge-mark.svg" alt=""></span><span class="brand-copy"><strong>FORGE</strong><small>Emotivus</small></span>'
def nav(p,current):
    items=[('Home',f'{p}index.html','home'),('Run Forge',f'{p}run/index.html','run'),('Project Truth',f'{p}truth/index.html','truth'),('Continuity & Evidence',f'{p}continuity/index.html','continuity')]
    links=''.join(f'<a href="{href}"'+(' aria-current="page"' if key==current else '')+f'>{label}</a>' for label,href,key in items)
    return f'<header class="topbar"><div class="shell nav"><a class="brand" href="{p}index.html" aria-label="Emotivus Forge home">{logo(p)}</a><button class="menu-toggle" type="button" data-menu-toggle aria-expanded="false" aria-controls="primary-links">Menu</button><nav class="links" id="primary-links" data-nav-links aria-label="Primary">{links}<a class="nav-download" href="{p}downloads/RUN-FORGE.zip">Download</a></nav></div></header>'
def footer(p): return f'<footer class="footer"><div class="shell"><div class="footer-grid"><div><a class="brand" href="{p}index.html">{logo(p)}</a><p>{esc(PRODUCT["tagline"])}</p><p class="site-domain">forge.emotivus.com</p></div><div><strong>Four pages</strong><div class="footer-links"><a href="{p}run/index.html">Run Forge</a><a href="{p}truth/index.html">Project Truth</a><a href="{p}continuity/index.html">Continuity & Evidence</a></div></div><div><strong>Exact files</strong><div class="footer-links"><a href="{p}downloads/RUN-FORGE.zip">Public runtime</a><a href="{p}downloads/SHA256SUMS.txt">Checksums</a><a href="{p}downloads/RELEASE-NOTES.md">Release notes</a><a href="https://emotivus.com">Emotivus.com</a></div></div></div><div class="footer-bottom"><span>Emotivus Forge · {VERSION} · Core reduction</span><span>Local-first · Portable · Model-collaborative</span><span>© <span data-year></span> Emotivus</span></div></div></footer>'
def shell(title,desc,body,current,depth=0,path=''):
    p=prefix(depth); structured={'@context':'https://schema.org','@type':'SoftwareApplication','name':'Emotivus Forge','applicationCategory':'DeveloperApplication','softwareVersion':VERSION,'url':BASE,'description':PRODUCT['summary']}
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#090706"><title>{esc(title)} — Emotivus Forge</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{canonical(path)}"><link rel="icon" href="{p}assets/favicon.svg" type="image/svg+xml"><link rel="manifest" href="{p}site.webmanifest"><link rel="stylesheet" href="{p}assets/styles.css"><script type="application/ld+json">{json.dumps(structured,separators=(',',':'))}</script><script src="{p}assets/app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>{nav(p,current)}{body}{footer(p)}</body></html>'''
def goal_cards():
    return ''.join(f'<article class="card"><span class="num">{g["id"]}</span><h3>{esc(g["name"])}</h3><p><strong>{esc(g["status"])}</strong></p><p>{esc(g["definition"])}</p></article>' for g in PRODUCT['active_roadmap']['goals'])
def home():
    body=f'''<main id="main"><section class="hero"><div class="shell hero-grid"><div><p class="eyebrow">The trust layer for AI-built software</p><h1>Give the model truth.<br><span>Let it do the work.</span></h1><p class="lead">{esc(PRODUCT['summary'])}</p><div class="actions"><a class="button primary" href="run/index.html">Run Forge</a><a class="button secondary" href="truth/index.html">See project truth</a></div><p class="release-note"><b>{VERSION}</b> · Sealed base · 523/523 checks across 54 modules · release not authorized.</p></div><aside class="forge-console"><div class="console-head"><span>Collaboration boundary</span><strong>Verified context</strong></div><div class="console-body"><div class="console-line"><span>Forge owns</span><strong>Identity · authority · evidence</strong></div><div class="console-line"><span>Model owns</span><strong>Reasoning · code · decisions</strong></div><div class="console-line"><span>Normal invocation</span><strong>Run Forge</strong></div><div class="console-line"><span>Unknown</span><strong>Stays NOT_RUN</strong></div><div class="console-line"><span>Roadmap</span><strong>Goals + scored evidence</strong></div></div></aside></div></section><section class="section"><div class="shell"><div class="section-head"><div><p class="eyebrow">Three outcomes</p><h2>No blended completion percentage.</h2></div><p>Two goals have binary completion gates. The third has a certifiable foundation and remains continuous.</p></div><div class="grid-3">{goal_cards()}</div></div></section><section class="section alt"><div class="shell"><div class="section-head"><div><p class="eyebrow">What survives better models</p><h2>Hashes, authority, pixels, and portable records.</h2></div><p>Guidance text may erode. Exact project truth does not.</p></div><div class="trust-strip"><div><b>Cross-vendor</b><span>Continuity is project-owned, not trapped in one model memory.</span></div><div><b>Deterministic</b><span>Evidence binds to exact files and packages.</span></div><div><b>Non-prescriptive</b><span>Forge does not tell the model how to think or code.</span></div><div><b>Reactive</b><span>New instruments require an observed miss and scored trial.</span></div></div></div></section></main>'''
    return shell('Home',PRODUCT['tagline'],body,'home')
def run_page():
    rows=[('No Forge state','Adopt enough project truth to orient, then Resume.'),('Valid state, unchanged','Resume with compact verified context.'),('Valid state, changed','Run scoped checks and refresh continuity.'),('Session ending','Close, export, and name the exact next action.'),('Release candidate','Assess evidence; never authorize or Ship automatically.'),('Authority conflict','Stop and name the artifact or decision that resolves it.')]
    cards=''.join(f'<article class="card"><h3>{a}</h3><p>{b}</p></article>' for a,b in rows)
    body=f'''<main id="main"><section class="page-hero"><div class="shell"><p class="eyebrow">One human invocation</p><h1>Run Forge.</h1><p class="lead">Forge reads deterministic project state, selects the bounded internal path, and gives the AI model verified context. The model remains free to reason and build.</p><div class="actions"><a class="button primary" href="../downloads/RUN-FORGE.zip">Download public runtime</a><a class="button secondary" href="../continuity/index.html">See the roadmap</a></div></div></section><section class="section"><div class="shell"><div class="section-head"><div><p class="eyebrow">Context routing</p><h2>Files determine the path.</h2></div><p>Named commands remain expert overrides during the transition. They are not the normal learning burden.</p></div><div class="grid-3">{cards}</div></div></section><section class="section alt"><div class="shell prose"><h2>Boundary</h2><p>Forge may identify, verify, summarize, and package. It does not choose product architecture, write the application, debug on the model's behalf, or prescribe a reasoning process.</p><pre><code>Run Forge</code></pre></div></section></main>'''
    return shell('Run Forge','One invocation that resolves project context without prescribing model behavior.',body,'run',1,'run')
def truth_page():
    body=f'''<main id="main"><section class="page-hero"><div class="shell"><p class="eyebrow">Goal 1</p><h1>Provable Project Truth.</h1><p class="lead">The durable Forge core identifies what project and package are real, what changed, what evidence belongs to them, and what remains unauthorized.</p></div></section><section class="section"><div class="shell"><div class="grid-3"><article class="card"><span class="num">IDENTITY</span><h3>Exact bytes</h3><p>Files, trees, packages, editions, versions, and embedded runtimes retain content identity.</p></article><article class="card"><span class="num">AUTHORITY</span><h3>Observed is not approved</h3><p>Unbaselined clean trees remain NOT_RUN. Exact reviewed authority is separate.</p></article><article class="card"><span class="num">LINEAGE</span><h3>Parents and rivals</h3><p>Forks, supersession, same-version collisions, quarantine, and recovery stay explicit.</p></article><article class="card"><span class="num">EVIDENCE</span><h3>Bound to its subject</h3><p>Checks, screenshots, DOM, receipts, and signatures cannot silently attach to another artifact.</p></article><article class="card"><span class="num">TRUTH STATES</span><h3>No false green</h3><p>PASS, FAIL, NOT_RUN, stale, contradicted, and blocked states keep distinct meaning.</p></article><article class="card"><span class="num">AUTHORIZATION</span><h3>One exact package</h3><p>Release authority remains explicit and cannot be inferred from lower evidence.</p></article></div></div></section><section class="section alt"><div class="shell prose"><h2>What Forge does not prove</h2><p>Forge does not authenticate human identity, establish legal authority, guarantee semantic correctness, replace native tests, or claim release readiness from incomplete evidence.</p><p><a href="../downloads/SHA256SUMS.txt">Verify current downloads</a> · <a href="../downloads/RELEASE-NOTES.md">Read release notes</a></p></div></section></main>'''
    return shell('Project Truth','Exact project identity, authority, lineage, evidence, and package truth.',body,'truth',1,'truth')
def continuity_page():
    goals=goal_cards(); active=[c for c in PRODUCT['active_roadmap']['chunks'] if c['status'] in ('COMPLETE','ACTIVE')]; queued=[c for c in PRODUCT['active_roadmap']['chunks'] if c['status']=='QUEUED'][:9]
    timeline=''.join(f'<article class="release"><strong>{c["id"]} · {c["timebox"]}</strong><div><h3>{esc(c["phase"])}</h3><p>{esc(c["work"])}</p><code>{c["status"]} · target {c["target_release"]}</code></div></article>' for c in active+queued)
    body=f'''<main id="main"><section class="page-hero"><div class="shell"><p class="eyebrow">Goals 2 and 3</p><h1>Continuity that can outlive today's models.</h1><p class="lead">Forge carries exact project truth between sessions and vendors, then evolves only through observed misses, migrations, and scored trials.</p></div></section><section class="section"><div class="shell"><div class="grid-3">{goals}</div></div></section><section class="section alt"><div class="shell"><div class="section-head"><div><p class="eyebrow">8–20 minute execution units</p><h2>Current and next chunks.</h2></div><p>The complete roadmap ships in the runtime and release documentation.</p></div><div class="timeline">{timeline}</div></div></section><section class="section"><div class="shell"><div class="section-head"><div><p class="eyebrow">Evidence scoreboard</p><h2>Value must be measured.</h2></div><p>No percentage can substitute for catches, misses, false positives, cold handoffs, or exact evidence.</p></div><div class="trust-strip"><div><b>Runtime map</b><span>88 of 88 modules classified across active surfaces.</span></div><div><b>Command paths</b><span>Run Forge plus five public commands observed in bounded fixtures.</span></div><div><b>Release authorization</b><span>False.</span></div><div><b>Release-ready</b><span>Not claimed.</span></div></div><p class="actions"><a class="button secondary" href="../downloads/RELEASE-NOTES.md">Release notes</a><a class="button secondary" href="../downloads/SHA256SUMS.txt">Checksums</a></p></div></section></main>'''
    return shell('Continuity & Evidence','Session continuity, outcome roadmap, release history, and evidence status.',body,'continuity',1,'continuity')
def build(download,notes,checksums):
    for d in ('run','truth','continuity','downloads'): (SITE/d).mkdir(parents=True,exist_ok=True)
    for obsolete in ('docs','roadmap','trust','changelog'):
        shutil.rmtree(SITE/obsolete,ignore_errors=True)
    (SITE/'index.html').write_text(home(),encoding='utf-8'); (SITE/'run'/'index.html').write_text(run_page(),encoding='utf-8'); (SITE/'truth'/'index.html').write_text(truth_page(),encoding='utf-8'); (SITE/'continuity'/'index.html').write_text(continuity_page(),encoding='utf-8')
    shutil.copy2(download,SITE/'downloads'/'RUN-FORGE.zip'); shutil.copy2(notes,SITE/'downloads'/'RELEASE-NOTES.md'); shutil.copy2(checksums,SITE/'downloads'/'SHA256SUMS.txt')
    urls=['','run','truth','continuity']; (SITE/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{canonical(u)}</loc></url>' for u in urls)+'</urlset>\n',encoding='utf-8')
    (SITE/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n',encoding='utf-8')
    return {'status':'PASS','version':VERSION,'pages':4,'navigation':WEB['primary_navigation']}
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--download',type=Path,required=True); ap.add_argument('--release-notes',type=Path,required=True); ap.add_argument('--checksums',type=Path,required=True); args=ap.parse_args(); print(json.dumps(build(args.download,args.release_notes,args.checksums),indent=2))
if __name__=='__main__': main()
